-- AlterTable
ALTER TABLE "AppSetting" ADD COLUMN IF NOT EXISTS "fafFliway" DECIMAL(10,2) NOT NULL DEFAULT 30.5;
ALTER TABLE "AppSetting" ADD COLUMN IF NOT EXISTS "fafMainfreight" DECIMAL(10,2) NOT NULL DEFAULT 36.35;
ALTER TABLE "AppSetting" ADD COLUMN IF NOT EXISTS "fafTge" DECIMAL(10,2) NOT NULL DEFAULT 29.8;
ALTER TABLE "AppSetting" ADD COLUMN IF NOT EXISTS "fafM2h" DECIMAL(10,2) NOT NULL DEFAULT 0;
