api_version = "2025-07"
uid = "f330209e-c097-0301-3bf4-3365da034a6d5a6822ae"

[[extensions]]
name = "order-freight-block"
handle = "order-freight-block"
type = "ui_extension"

  [[extensions.targeting]]
  module = "./src/BlockExtension.tsx"
  target = "admin.order-details.block.render"
