api_version = "2025-07"
uid = "e04a8f28-7451-9ba1-b0ff-ade7485de409441a6c2b"

[[extensions]]
type = "ui_extension"
name = "depot-child-selector"
handle = "depot-child-selector"

[[extensions.targeting]]
target = "purchase.checkout.shipping-option-item.render-after"
module = "./src/Checkout.tsx"